export * from './static-icon.model'
export * from './static-icon.module'
export * from './static-icon.service'
export * from './static-icon-img/static-icon-img.component'
export * from './static-icon-form-field/static-icon-form-field.component'
export * from './static-icon-select/static-icon-select.component'