services:
  mage-idp-saml:
    container_name: mage-idp-saml
    image: kristophjunge/test-saml-idp
    environment:
      - "SIMPLESAMLPHP_SP_ENTITY_ID=http://localhost:4242"
      - "SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:4242/auth/saml/callback"
      - "SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=http://localhost:8080/simplesaml/module.php/saml/sp/saml2-logout.php/test-sp"
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - type: bind
        source: ./saml/authsources.php
        target: /var/www/simplesamlphp/config/authsources.php

