name: Build and Run Tests

on:
  push:
    branches-ignore:
      - 'no-ci-*'
      - 'wip-*'
      - 'x-*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dev tools
      run: |
        sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
    - name: Server install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Web install, build, and test
      run: |
        cd web-app
        npm install
        npm run build --if-present
        npm run test-headless
      env:
        CI: true
        NODE_OPTIONS: "--max_old_space_size=4096"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$JOB_CONTEXT"
    - name: Coveralls
      if: matrix.node-version == '14.x'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./docs/coverage/lcov.info