name: build and test web-app

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - web-app/**
      - .github/workflows/build_test.web-app.yaml
      - .github/workflows/config.yaml

jobs:
  config:
    uses: ./.github/workflows/config.yaml
  main:
    name: build mage web app
    needs: config
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.config.outputs.node_versions-lts }}
          cache: npm
          cache-dependency-path: web-app/package-lock.json
      - name: build
        run: |
          cd web-app
          npm ci
          npm run build:prod
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: test
        run: |
          cd web-app
          npm run ci:test
      - name: pack
        run: |
          npm pack ./web-app/dist/core-lib
          npm pack ./web-app/dist/app
      - name: upload packages
        uses: actions/upload-artifact@v3
        with:
          name: mage_web-app_packages
          path: |
            ngageoint-mage.*.tgz