name: Production Container Build

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: |
          Supply a tag to push the image to ghcr.io with the given tag.  Without a tag, the workflow will not push,
          but only build the image.
        type: string
        required: false

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Registry ghcr.io
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: image-info
        id: image-info
        run: |
          image_tag="local"
          [[ ${{ github.ref }} = 'refs/heads/develop' ]] && image_tag="dev"
          [[ -n "${{ inputs.image-tag }}" ]] && image_tag="${{ inputs.image-tag }}"
          image_url="${{ github.repository }}/mage-prod:${image_tag}"
          image_version=$(jq -r .version < ./service/package.json)
          echo "using image url ${image_url}"
          echo "tag=${image_tag}" >> $GITHUB_OUTPUT
          echo "url=ghcr.io/${image_url}" >> $GITHUB_OUTPUT
          echo "version=${image_version}" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          file: ./docker/server/Dockerfile
          tags: ${{ steps.image-info.outputs.url }}
          platforms: linux/amd64
          push: ${{ steps.image-info.outputs.tag }} != local
          annotations: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.image-info.outputs.version }}

      - name: Scan the docker image with Trivy
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: 'image'
          image-ref: '${{ steps.image-info.outputs.url }}'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-image-report.txt'
          exit-code: '0'
          version: 'v0.69.3'

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-container-security-report
          path: trivy-image-report.txt
          retention-days: 7
