name: Production Container Build

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to Github Registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/mage:$IMAGE_TAG ./docker/server

      - name: Push Image
        if: github.ref =='refs/heads/test' || github.ref =='refs/heads/develop'
        run: |
          docker push ghcr.io/${{ github.repository }}/mage:$IMAGE_TAG
