name: Security Scan
on: [push, pull_request]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          output: 'trivy-report.txt'
          exit-code: '0'

      - name: Upload Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: trivy-report.txt
          retention-days: 7